webpack-contrib/extract-text-webpack-plugin

README.md, example/webpack.config.js
as per http://webpack.github.io/docs/configuration.html#devtool
=> Change 'sourcemap' to 'source-map'

index.js
Current if the loaders are specified as an array, then extract will
assume they are the options. If the `notExtractLoader` is specified as
an array then there will be an error when trying to split it.
It might be best to only support this change if `loaders:` is used
instead of `loader:` but even solving that problem at all seems to be
a larger issue. This at least allows for using an array of loaders
even if it still must be in a `loader:` context.
=> Support loaders specified as an array

package.json
Version 1.0.0 depends on `webpack-sources`, but it does not specify this in `package.json`. See 39d9cc85388c64ed775d09d467c49bd577b50e8b.
```
03 01 2016 22:10:04.273:ERROR [config]: Invalid config file!
Error: Cannot find module 'webpack-sources'
at Function.Module._resolveFilename (module.js:327:15)
at Function.Module._load (module.js:278:25)
```
=> Fix: Add dependency for webpack-sources

README.md
Added a example use case of multiple plugin instances in `README.md`.
=> Add example for multiple plugin instances

example/webpack.config.js, index.js, loader.js, test/TestCases.test.js
Node v6 does not resolve symlink anymore using __dirname. This pull fixes error messages like:
```
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
```
when node_modules is symlinked.
=> fix(symlink): node v6 symlink resolve update

index.js, test/cases/simple-queryless-object/a.css, test/cases/simple-queryless-object/b.css, test/cases/simple-queryless-object/expected/file.css, test/cases/simple-queryless-object/index.js, test/cases/simple-queryless-object/webpack.config.js
If you provide a loader as an object *without* query config, the entire object currently gets returned from `getLoaderWithQuery()` and ends up being stringified as `[object Object]` in the final loader string generated.
=> Fix handling of loaders as objects without a query prop

package.json
This is not actually API-compatible with any webpack beta older than 2.1.0-beta.19.
=> Be more specific on the peerDependencies

index.js, test/extract.test.js
This allows you to `use:` the output of `extract()` by not munging everything into a string (which `use` config should obviate the need for in Webpack 2).
It's far less surprising and makes it possible to [provide plugins to preprocessor loaders directly via loader `options`](https://github.com/webpack/extract-text-webpack-plugin/issues/265#issuecomment-273773975) instead of messing around with `LoaderOptionsPlugin`
This change is as per tmair@1414036 - if @tmair wants to create their own PR for it, I'm happy to close this one.
=> Return an array of loader objects from extract()

CHANGELOG.md, RELEASE.md, package.json
As discussed in webpack/webpack#4104
- Adds standard-version
- Adds documentation for generating various tags
- Adds empty changelog ( will require some `reword` work to get the full history )
=> chore(release): add standard version & documentation

loader.js, package.json
Using just the serialized request means that query objects (that is to say, those which are not strings), get munged if they have anything non-serializable in them. This means passing data to `postcss` via `query` is impossible. To remedy this, we detect when the original request is being processed and apply the original loader transformations instead of whatever came through the serialized version.
Build seems to be _only_ failing on `node@0.12` but `webpack@2` doesn't support that.. so..
See:
- https://github.com/postcss/postcss-loader/pull/104
- https://github.com/webpack-config/webpack-config-postcss/pull/10
/cc @sokra
=> Pass proper loader `options` to children.

README.md
=> fix(readme) - Fix typo

README.md
Noticed that documentation is outdated for the `options.use` and the `options.fallback` types. As far as I can tell, they should also be able to be an array (especially since they are replacing the `fallbackLoader` and the `loader` options and they were able to be arrays): https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/master/schema/loader-schema.js
=> docs - adds array type for options.use and options.fallback

README.md
There's been a lot of issues regarding extracting Sass/LESS. I hope this readme will make things easier for others.
This worked for me on `Node 7.5.0` and `webpack@2.2.1`. I can provide an example repo.
=> Make documentation regarding extracting Sass/LESS clearer

ExtractedModule.js
this will be removed from webpack and should arguably never been used in the first place
=> inline removeAndDo dep to webpack internal lib

README.md
These instructions are outdated as of the `2.0.0` release, published to npm a couple of hours before this pull request was submitted.
Without these changes, following the directions for installation alongside webpack 1 results in an "unmet peer dependency" error.
=> Update README.md to reflect version changes

README.md
Both source types `.css` and `.less` will result in pure CSS content after `css-loader`. So it's expected that the extension for the extracted file will always be `.css`.
=> Fix "Multiple Instances" example

test/extract.test.js
Added testcase for :
```js
ExtractTextPlugin.extract({
use: ["css-loader", "postcss-loader", "sass-loader"]
});
```
and
```js
ExtractTextPlugin.extract({
use: [
{ loader: "css-loader", options: { modules: true } },
"postcss-loader"
]
});
```
to make sure them work well.
=> Added two tests to extract

index.js
This check will fix #42 for webpack2 users.
=> fix: add a not null check for the content property before throwing error

README.md
See webpack/webpack.js.org#1161 and [this page](https://webpack.js.org/plugins/extract-text-webpack-plugin/) in the docs which lacks a good lead-in sentence.
=> docs(README): add lead-in description

loader.js
=> fix(loader): rm unnecessary `this.cacheable` (caching)

index.js
=> fix(index): resolve schemas relative to `__dirname`

index.js
https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/520 Adds an option: "ignoreOrder" this is not listed in the available options in the error output for this plugin. Which can be confusing.
=> fix: add missing `options.ignoreOrder` details in Error message

loader.js
This is recommended after https://github.com/webpack/webpack/pull/4704
It's not good to merge before this PR because it would create absolute paths in the records.
Closes #389
=> refactor: pass a unique compiler name to get child compilation (webpack 3)

package.json, src/index.js, test/cases/chunk-modules-ordered-by-id/a.js, test/cases/chunk-modules-ordered-by-id/b.txt, test/cases/chunk-modules-ordered-by-id/c.txt, test/cases/chunk-modules-ordered-by-id/expected/file.css, test/cases/chunk-modules-ordered-by-id/index.js, test/cases/chunk-modules-ordered-by-id/webpack.config.js
Replaces remaining usage of the deprecated `chunk.modules` functions
BREAKING CHANGE: Updates to `Chunk.mapModules | forEachModule | getNumberOfModules`. This release is not backwards compatible with `Webpack 2.x` due to breaking changes in webpack/webpack#4764
Closes #548
=> refactor: Update deprecated `chunk.modules` functions

src/index.js, test/__snapshots__/webpack-integration.test.js.snap
=> fix(index): CSS module sorting (`extractedChunk.sortModules(cb)`)

src/index.js
- module was incorrectly being passed to the sort function with throws a type error in certain circumstances.
Fixes #565
Fixes #554
=> fix: Modules shouldn't be passed to sort

README.md
In README, document the ability to use `[<hashType>:contenthash:<digestType>:<length>]` in filenames. This feature is similarly documented in the README of [hash-loader](https://github.com/webpack-contrib/file-loader/blob/master/README.md).
=> docs(README): add custom `[contenthash]` formats

src/index.js
Tried this on a few projects that been having this issue and it works
---
Fixes https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/604
=> fix(index): stricter check for `shouldExtract !== wasExtracted`

src/index.js, src/loader.js
Without this fix, this plugin doesn't work if your node_modules tree is
made up of real directories, but your files are symlinks. It's admittedly a
weird environment, but that's the environment that the Bazel build
system runs code in, which is the build system we use at Dropbox.
This is the bug:
- index.js is called from the runfiles directory, and it uses the
realpath of its directory as the key for a function on the
loaderContext object.
- loader.js is called from the bazel-bin/npm directory outside
of its runfiles (because Webpack escapes the runfiles when it
calls loaders). It uses the realpath of its directory as a
key on the loaderContext object, but because it's in a
different directory from index.js, it can't find the function
set on the loaderContext by index.js.
The fix is to …
=> fix: get realpath from `__filename` instead of `__dirname` (`NS`)

.babelrc, .travis.yml, appveyor.yml, package-lock.json, package.json
- Updates to minimum Node version of 4.8 ( npm 5 compatibility )
- Update devDependencies via `npm run webpack-defaults`
- Semantic changes to both CI configurations
=> build(defaults): update to v1.6.0

README.md
I was scouring the internet looking for how to get my css url() to resolve when webpack compiles. I couldn't find anything! But, I took a guess at setting `url: false` in the options for my loader and it worked! It would be beneficial to have this documentation on the readme. Thanks for the awesome plugin!
=> docs(README): add example how-to disable `url()` resolving

README.md
* mention deprecation of ETWP for css usage for webpack v4+
* link to `mini-css-extract-plugin`
Fixes webpack/webpack.js.org#2001
=> docs(readme) WP4 deprecation for css. Link to MiniCSSExtractPlugin

package.json
We should remove webpack@3.0.0 as a "peerDependencies" to this version of extract-text-webpack-plugin.
extract-text-webpack@next (4.0.0-beta.0) is not compatible with webpack 3.x. I am assuming this is the direction you are going with this plugin (correct me if I am wrong). For example, this is the incompatibility line I faced that is problematic if `webpack@3.x` is used:
https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/34e508342df9c4fb3fb2a3ddef4700c5a58f9fb0/src/index.js#L222
Let's assume you have an application that uses `webpack@3.x` and a packages `A` that uses `webpack@4.x` and `extract-text-webpack@next`. When installing the dependencies, `extract-text-webpack` gets installed in the root `node_modules` not `node_modules/A/node_modules`. This obviously forces …
=> fix(package): remove `webpack =< v3.0.0` (`peerDependencies`)

src/loader.js
I've found the [commit][1] where it was introduced. My conjecture is that `webpack` didn't add this dependency itself back then. Or this line was added just in case.
[1]: https://github.com/webpack-contrib/extract-text-webpack-plugin/commit/f7d5bbf1c4eb3fab60c7656aece076d3d5c06912
If I've got to back it with tests, then I might need your help. My idea is to add a couple of tests to [`test/webpack-integration.test.js`][2], since putting it into `test/cases` doesn't seem like an option. Tests from the latter dir expect on the files output by `webpack`. With dependencies you've got to hook into compilation process. Supposedly how I did in the issue. That would probably be the best way.
Also, can you explain what dependency adds [this line][3] to save me some time? Between what and what …
=> fix(loader/pitch): unnecessary addition of redundant `fileDependencies` (`this.addDependency`)
